### Create Plan

POST http://localhost:3000/plan
Content-Type: application/json
Authorization: aa0800f9-69d1-43e7-8255-1006a99e84f2

{
    "title": "Tehran shomal highway"
}

###

GET http://localhost:3000/plan/1

###

POST http://localhost:3000/plan
Content-Type: application/json

{
    "title": ""
}

### Login

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}